name: 'Fetch Dependabot Alerts'
description: 'Fetches GitHub data and reports in the Actions summary'
inputs:
  org_name:
    description: 'GitHub organization name'
    required: true
  repo_name:
    description: 'GitHub repository name'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

# name: 'Dependabot Alerts Fetcher'
# description: 'Fetch Dependabot alerts for an organization or repository'
# branding:
#   icon: 'inbox'
#   color: 'blue'
# inputs:
#   org_or_repo:
#     description: 'Organization or repository name'
#     required: true
#   github_token:
#     description: 'GitHub token'
#     required: true
# runs:
#   using: 'docker'
#   image: 'Dockerfile'
#   args:
#     - ${{ inputs.org_or_repo }}
#     - ${{ inputs.github_token }}
